repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: deploy/.*
      - id: check-added-large-files
        args: [--maxkb=100000]
      - id: check-json
        exclude: .devcontainer

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.5.1
    hooks:
      - id: pip-compile
        name: production dependencies
        files: requirements/requirements.in
        args:
          - requirements/requirements.in
      - id: pip-compile
        name: development dependencies
        files: requirements/requirements-dev.in
        args:
          - requirements/requirements-dev.in


  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: app/migrations/versions/.*

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args:
          [--no-strict-optional, --ignore-missing-imports, --show-error-codes]
        additional_dependencies:
          - pydantic
          - types-pytz
          - types-python-dateutil
          - types-python-slugify
          - types-requests

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.4
    hooks:
      - id: pycln
        args: [--all]
        exclude: app/migrations/
        additional_dependencies:
          - "click<8.1.0"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          [--profile, black]
